### ISSUE TITLE
Achievement suggestions

### ISSUE THREAD

**Issue by nickpeihl** [SJCGIS/footprint-review#1]
> Eagle Eye? Inspector Detector? Sasquatch Spotter? Needle 'n Haystack? House Hunter? OCD PhD?

from Greg S.

**Comment by npeihl** [comment]
Drama Derry. Eager beaver. Bailiff. Fixer upper.  House flipper. Skipper. Flagger. Doggone polygon. Mapmaker matchmaker. Wingmate.

**Comment by jgravois** [comment]
these are *all* gold.

**Comment by npeihl** [comment]
Thanks, one of those things I need to figure out is how far apart to spread the achievements to keep folks interested.

**Comment by jgravois** [comment]
i think its pretty common for additional levels to get exponentially more difficult to unlock...

**Comment by nickpeihl** [comment]
I don't expect we'll be adding any more achievements at this time.
