### ISSUE TITLE
Share button doesn't work on new achievements

### ISSUE THREAD

**Issue by nickpeihl** [SJCGIS/footprint-review#10]
The share button won't show the menu on newly unlocked achievements. After the page is refreshed the share button does work. Likely has something to do with yo-yo.

**Comment by npeihl** [comment]
Also having same issue when not using yo-yo in 59ecb8a .

**Comment by nickpeihl** [comment]
See also https://github.com/SJCGIS/footprint-review/issues/6#issuecomment-262007888
