### ISSUE TITLE
Guidance on what to do about porches and decks?

### ISSUE THREAD

**Issue by taylori** [SJCGIS/footprint-review#12]
Instructions would benefit from guidance on what to consider part of the "building footprint" with regard to things like porches and decks.
Software is brilliant, by the way, just reviewed 100 sets, and thanks for supporting OpenStreetMap.

**Comment by npeihl** [comment]
Thanks for the comment. Ignore porches and decks. Eaves make the best footprint outlines. 

I'll see about adding that info to the instructions.

**Comment by npeihl** [comment]
Fixed by de57b1cb

**Comment by taylori** [comment]
Looks great. Thank you!
