### ISSUE TITLE
Add share menu to achievements

### ISSUE THREAD

**Issue by nickpeihl** [SJCGIS/footprint-review#6]
Folks love to share their accomplishments on social media. Let's add a [Share menu](http://getmdl.io/components/index.html#menus-section) to the achievement cards. 
- [x] Twitter
- [x] Facebook

**Comment by npeihl** [comment]
Fix in  fc04aa4

**Comment by nickpeihl** [comment]
This is currently not possible in mdl with the way we are dynamically creating the cards
